language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "3.4"

before_install:
    - pip install toolz==0.7.1

install:
    - python setup.py build_ext --inplace --without-cython

# commands to run tests
script:
    - nosetests --with-doctest cytoolz

notifications:
  email: false
