language: python
python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"

before_install:
    - pip install git+https://github.com/pytoolz/toolz.git

install:
    - python setup.py build_ext --inplace --without-cython

# commands to run tests
script:
    - nosetests --with-doctest cytoolz

notifications:
  email: false
