package:
    name: cytoolz
    version: "0.6.1"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}
    script: 
      - cd $RECIPE_DIR
      - $PYTHON setup.py install --with-cython

requirements:
    build:
      - setuptools
      - python
      - cython
      - toolz

    run:
      - python

about:
    home: http://toolz.readthedocs.org/
    license: BSD
