package:
    name: cytoolz
    version: "0.7.1"

build:
    number: {{environ.get('BINSTAR_BUILD', 1)}}

requirements:
    build:
      - setuptools
      - python
      - cython
      - toolz

    run:
      - python

test:
    requires:
      - pytest
      - nose
    imports:
      - cytoolz
    commands:
      - py.test -x --doctest-modules --pyargs cytoolz

about:
    home: http://toolz.readthedocs.org/
    license: BSD
